### ISSUE TITLE
wasm builds of box2d and liquidfun

### ISSUE THREAD

**Issue by danbri** [Lusito/box2d.ts#24]
What would it take to integrate https://github.com/Birch-san/box2d-wasm/releases/tag/v4.0.0-liquidfun.0 i to the benchmarks?

**Comment by Lusito** [comment]
Good question.. if you only want to compare the pure box2d performance, then it should be relatively easy by:
- adding `liquidfun-wasm` to the dependencies of the benchmark
- Creating a Test file, just follow one of the existing examples: https://github.com/Lusito/box2d.ts/blob/master/packages/benchmark/src/tests/box2d-js.ts
- Importing it to the testMap https://github.com/Lusito/box2d.ts/blob/master/packages/benchmark/src/tests/testMap.ts

**Comment by Lusito** [comment]
If you want to compare the liquidfun parts, you'd have to first create a test setup to actually compare it and create a separate entry-point, since not all of the libraries support particles. Maybe use the [Soup stirrer](https://lusito.github.io/box2d.ts/testbed/#/Particles#Soup_Stirrer) as a base?
