### ISSUE TITLE
Constructor of class 'b2World' is private and only accessible within the class declaration

### ISSUE THREAD

**Issue by 8Observer8** [Lusito/box2d.ts#25]
Hi,

How to solve it?

![image](https://user-images.githubusercontent.com/3908473/187068524-cd53ee59-ea28-44af-9f39-cef53013e185.png)

**Comment by Lusito** [comment]
Hi,

the constructor is private in order to allow the extension libraries to work.
Use `b2World.Create(gravity)` instead.

**Comment by 8Observer8** [comment]
Thank you very much!
