### ISSUE TITLE
Hasn't the DebugDraw() method been implemented?

### ISSUE THREAD

**Issue by 8Observer8** [Lusito/box2d.ts#27]
I do not see this method in IntelliSense:

![image](https://user-images.githubusercontent.com/3908473/187078027-0486d199-ad2a-4049-8bd6-e5c93726369a.png)

**Comment by Lusito** [comment]
There is no public API for this yet, see #23.

**Comment by 8Observer8** [comment]
Solution is [here](https://github.com/Lusito/box2d.ts/issues/33#issuecomment-1387710668).
