### ISSUE TITLE
Hello World example

### ISSUE THREAD

**Issue by bigidea-kz** [Lusito/box2d.ts#29]
Hello! 
I don't know if this is a bug or I don't understand something

"dependencies" : "@box2d/core": "^0.10.0"

I try this code

![Снимок экрана 2022-09-30 в 00 44 45](https://user-images.githubusercontent.com/44386084/193116581-6111e2f2-17b4-4b3c-bed2-dc3984701564.png)

console log output
![Снимок экрана 2022-09-30 в 00 44 09](https://user-images.githubusercontent.com/44386084/193116697-98ce700a-c487-4ed2-be58-b59fc8f994bf.png)

**Comment by Nek-** [comment]
Hello,

Demo are available here: https://lusito.github.io/box2d.ts/testbed/

And the code is here: https://github.com/Lusito/box2d.ts/tree/master/packages/testbed

**Comment by bigidea-kz** [comment]
Thanks :)
