### ISSUE TITLE
`DrawSolidPolygon` gets wrong collider position

### ISSUE THREAD

**Issue by 8Observer8** [Lusito/box2d.ts#35]
box2d-core 0.10.0
JavaScript

`DrawSolidPolygon` gets wrong collider position: https://plnkr.co/edit/GU2srU06SAzySUg6

![image](https://user-images.githubusercontent.com/3908473/214068730-6c7ea223-1737-46c4-9c73-8c568690332d.png)

I try to set collider position in `main.js` here:

```js
    const groundBody = world.CreateBody({ type: b2BodyType.b2_staticBody,
        position: { x: groundPosition[0] / pixelsPerMeter,
        y: groundPosition[1] / pixelsPerMeter}});
```

But I have wrong line positions in `debug-drawer.js`:

```js
    DrawSolidPolygon(vertices, vertexCount, color) {
        // console.log(vertices);
        // console.log(color);
        mat4.mul(this.projViewMatrix, this.projMatrix, this.viewMatrix);
        gl.uniform3f(this.uColorLocation, color.r, color.g, color.b);
        this.drawLine(vertices[0], vertices[1]);
        this.drawLine(vertices[1], vertices[2]);
        this.drawLine(vertices[2], vertices[3]);
        this.drawLine(vertices[3], vertices[0]);
    }
```

I ported this example to [box2d-wasm v7.0.0](https://www.npmjs.com/package/box2d-wasm?activeTab=readme) and it works fine: https://plnkr.co/edit/exqhktfXnvxwtBRq

![debug-drawer-box2dwasm-js](https://user-images.githubusercontent.com/3908473/214072546-92d62972-4066-4025-aa6a-afa94434bf22.gif)

**Comment by Lusito** [comment]
Are you aware of PushTransform/PopTransform within the b2Draw interface?
[PushTransform(xf:](https://github.com/Lusito/box2d.ts/blob/072d817b70b19e17215135ea20a241af659e6925/packages/debug-draw/src/index.ts#L56)

The vertices might not be in their final position. You need to take the transforms into account

**Comment by 8Observer8** [comment]
I added `console.log(xf)` here:

```js
    PushTransform(xf) {
        console.log(xf);
    }
```

I see the offset:
![image](https://user-images.githubusercontent.com/3908473/214665027-ec15af8b-662b-4573-bc87-648f931c17ff.png)

I create a new vector in the constructor:

```js
    constructor(program, pixelsPerMeter) {
        /* ... */
        this.xf = vec3.create();
    }
```

I load an offset vector before drawing:

```js
    PushTransform(xf) {
        this.xf[0] = xf.p.x * this.pixelsPerMeter;
        this.xf[1] = xf.p.y * this.pixelsPerMeter;
    }
```

I apply the offset before drawing:

```js
vec3.add(this.position, this.position, this.xf);
```

And it works: https://plnkr.co/edit/GU2srU06SAzySUg6

![image](https://user-images.githubusercontent.com/3908473/214670392-2a6b8c7a-0208-491f-a5c8-097f521ad685.png)

Thank you very much!

P.S. As you can see in this example, I'm drawing the colliders behind the object:

```js
function draw() {
    gl.clear(gl.COLOR_BUFFER_BIT);
    DrawShapes(debugDrawer, world);

    mat4.fromTranslation(modelMatrix, groundPosition);
    mat4.rotateZ(modelMatrix, modelMatrix, 0);
    mat4.scale(modelMatrix, modelMatrix, groundSize);
    mat4.mul(mvpMatrix, projViewMatrix, modelMatrix);
    gl.uniformMatrix4fv(uMvpMatrixLocation, false, mvpMatrix);
    gl.uniform3fv(uColorLocation, groundColor);
    gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
}
```

because in this case I can see the boundaries of the object. If the colliders are drawn on top of the object, it looks bad in this example:

```js
function draw() {
    gl.clear(gl.COLOR_BUFFER_BIT);

    // Ground
    mat4.fromTranslation(modelMatrix, groundPosition);
    mat4.rotateZ(modelMatrix, modelMatrix, 0);
    mat4.scale(modelMatrix, modelMatrix, groundSize);
    mat4.mul(mvpMatrix, projViewMatrix, modelMatrix);
    gl.uniformMatrix4fv(uMvpMatrixLocation, false, mvpMatrix);
    gl.uniform3fv(uColorLocation, groundColor);
    gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);

    DrawShapes(debugDrawer, world);
}
```

![image](https://user-images.githubusercontent.com/3908473/214672643-7be9b126-1357-4d5c-9015-1e3be4ba401e.png)

**Comment by Lusito** [comment]
Just so you know, the transformation is not just a positional offset, but also a rotation. If that doesn't matter for your example, fine. Otherwise you will end up with drawing issues when your bodies start rotating.

**Comment by 8Observer8** [comment]
> the transformation is not just a positional offset, but also a rotation

I see the problem. I'll try to fix it by myself. If I can't, I'll create an issue.

![debug-drawer-box2dcore-webgl-js-collider-rotation-problem](https://user-images.githubusercontent.com/3908473/214708491-d0327923-ca40-487a-848f-cf80f9f89997.gif)

**Comment by 8Observer8** [comment]
I tried to use `quat.rotateZ(this.rotation, this.rotation, this.radianOffset);` and got this cool effect:

![debug-drawer-box2dcore-webgl-js-first-trying-to-fix-a-rotation-problem](https://user-images.githubusercontent.com/3908473/214710454-7bd14a3b-de14-416b-a273-ba1e832001e8.gif)

**Comment by 8Observer8** [comment]
Rotation problem with box2d-core and WebGL: https://github.com/Lusito/box2d.ts/issues/36
