### ISSUE TITLE
Links in documentation don't work on local server

### ISSUE THREAD

**Issue by 8Observer8** [Lusito/box2d.ts#41]
I installed a local server globally:

> npm i -g http-server

I downloaded the repository, went to the documentation folder and started the local server:

> http-server

Opened the browser and entered the address:

> localhost:8080/index.html

There is a page with links: "Benchmarks", "Demos", "Documentation" and "GitHub". But when I try to click "Benchmarks", "Demos", "Documentation" I see these links:

- http://localhost:8080/benchmark//////////////////////////////////////
- http://localhost:8080/testbed//////////////////////////////////////
- http://localhost:8080/docs//////////////////////////////////////

and the message:

![image](https://github.com/Lusito/box2d.ts/assets/3908473/c2d5d6f7-39ed-4699-97dc-cafef022d30a)

**Comment by Lusito** [comment]
Thanks for the report. The docs are in the process of being rewritten completely. When I'm done, everything should be working.

**Comment by Lusito** [comment]
Docs have been updated. Now all the original docs have also been incorporated and adjusted accordingly. Let me know if you still have issues.
